POST http://localhost:3002/users
Content-Type: application/json

{
  "name": "Matheus M Militão",
  "username": "matheus",
  "password": "1234"
}

#### criar outro usuario

POST http://localhost:3007/users
Content-Type: application/json

{
  "name": "Carla Militão",
  "username": "carla",
  "password": "123456"
}


#### criar outro usuario

POST http://localhost:3002/users/register
Content-Type: application/json

{
  "name": "Eriks BMS",
  "username": "eriksbms",
  "password": "1234",
  "idEmpresa": "2e59d1e7-13c5-418f-a247-6afd586e06ec"
}


#### auth user
POST https://unledu-api-wpp.qltz9y.easypanel.host/users/auth
Content-Type: application/json

{
  "userName": "eriksbms",
  "password": "1234"
}

