POST http://localhost:3007/users
Content-Type: application/json

{
  "name": "Matheus M Militão",
  "username": "militao234",
  "password": "1234"
}

#### criar outro usuario

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Carla Militão",
  "username": "carla",
  "password": "123456"
}


#### criar outro usuario

POST http://localhost:3007/users/register
Content-Type: application/json

{
  "name": "Bernardo Militão",
  "username": "bernardo3434",
  "password": "1234"
}

