POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Matheus M Militão",
  "username": "militao",
  "password": "123456"
}

#### criar outro usuario

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Carla Militão",
  "username": "carla",
  "password": "123456"
}


#### criar outro usuario

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Bernardo Militão",
  "username": "bernardo",
  "password": "123456"
}

